Improve output()
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/mget.sh.in b/src/prg/bash/mget.sh.in
--- a/src/prg/bash/mget.sh.in
+++ b/src/prg/bash/mget.sh.in
@@ -130,7 +130,7 @@
 script_exit_code=0
 version=1.2.1				# set version variable
 etclocation=@sysconfdir@		# Path to etc directory
-outputprefix="$(basename $0): "
+outputprefix="$(basename $0):"
 packageversion=@pkgversion@		# Version of the complete package
 
 conffile=".mget"
@@ -176,13 +176,17 @@ Usage is $0 [OPTIONS]
 EOF
 }
 
-# Output $1 to stdout or stderr depending on $2
+# Standard function to emit messages depending on various parameters.
+# Parameters -	$1 What:-	The message to emit.
+#		$2 Where:-	stdout == 0
+#				stderr == 1
+# No return value.
 output()
 {
-	if (( ! $2 )); then
-		echo "$outputprefix$1"
+	if (( !$2 )); then
+		printf "%s %s\n" $outputprefix "$1"
 	else
-		echo "$outputprefix$1" 1>&2
+		printf "%s %s\n" $outputprefix "$1" 1>&2
 	fi
 }
 
