Release 1.0.10. Tidied up use of output function. multiget script now at version 1.0.10

diff --git a/scripts/scriptssrc/multiget.in b/scripts/scriptssrc/multiget.in
--- a/scripts/scriptssrc/multiget.in
+++ b/scripts/scriptssrc/multiget.in
@@ -77,6 +77,7 @@
 ##				only place to insert the program name	##
 ##				and it uses $0.				##
 ## 15/12/2013	MG	1.0.9	Use command name instead of $0.		##
+## 01/01/2014	MG	1.0.10	Tidied up use of output function.	##
 ##									##
 ##########################################################################
 
@@ -85,8 +86,9 @@
 ## Init variables ##
 ####################
 script_exit_code=0
-version="1.0.9"			# set version variable
+version="1.0.10"		# set version variable
 etclocation=@sysconfdir@	# Path to etc directory
+outputprefix="multiget: "
 
 # Get system name for implementing OS differeneces.
 osname=$(uname -s)
@@ -109,24 +111,24 @@ output()
 {
 	if [ $2 = 0 ]
 	then
-		echo "multiget: $1"
+		echo "$outputprefix$1"
 	else
-		echo "multiget: $1" 1>&2
+		echo "$outputprefix$1" 1>&2
 	fi
 }
 
-# Standard function to announce $1 and return exit code
+# Standard function to tidy up and return exit code
 script_exit()
 {
-	output $1 $script_exit_code
 	exit $script_exit_code
 }
 
 # Standard trap exit function
 trap_exit()
 {
-	script_exit_code=67
-	script_exit "Script terminating due to trap received. Code: "$script_exit_code
+script_exit_code=67
+output "Script terminating due to trap received. Code: "$script_exit_code 1
+script_exit
 }
 
 # Setup trap
@@ -187,7 +189,8 @@ do
 		echo "	'-t targetdir' Name of directory for storing retrieved files."
 		echo "	'-v' Displays version information."
 		echo "	'-w' Use Windows CR/LF line endings instead of Unix LF line endings."
-		exit 0
+		script_exit_code=0
+		script_exit
 		;;
 	o)	owner=TRUE
 		newowner=$OPTARG
@@ -201,15 +204,18 @@ do
 	t)	targetdir=$OPTARG
 		;;
 	v)	echo "$0 version "$version
-		exit 0
+		script_exit_code=0
+		script_exit
 		;;
 	w)	windows=TRUE
 		;;
 	:)	script_exit_code=64
-		script_exit "Must supply an argument to -$OPTARG."
+		output "Must supply an argument to -$OPTARG." 1
+		script_exit
 		;;
 	\?)	script_exit_code=64
-		script_exit "Invalid argument -$OPTARG."
+		output "Invalid argument -$OPTARG." 1
+		script_exit
 		;;
 	esac
 done
@@ -217,20 +223,23 @@ done
 # If only persist flag set then nothing to do, exit.
 if [ $# = 1 -a "$1" = "-p" ]
 then
-	exit 0
+	script_exit_code=0
+	script_exit
 fi
 
 # Check source file exists and is readable.
 if [ ! -f "$sourcefile" ]
 then
 	script_exit_code=66
-	script_exit "Source file not valid."
+	output "Source file not valid." 1
+	script_exit
 fi
 
 if [ ! -r "$sourcefile" ]
 then
 	script_exit_code=77
-	script_exit "Source file not accessible."
+	output "Source file not accessible." 1
+	script_exit
 fi
 
 # Now ensure source file is in Unix text format.
@@ -245,13 +254,15 @@ fi
 if [ ! -d "$targetdir" ]
 then
 	script_exit_code=66
-	script_exit "Target directory not valid."
+	output "Target directory not valid." 1
+	script_exit
 fi
 
 if [ ! -w "$targetdir" ]
 then
 	script_exit_code=77
-	script_exit " Target directory not accessible."
+	output "Target directory not accessible." 1
+	script_exit
 fi
 
 # Now get the files
@@ -262,21 +273,19 @@ do
 	outputfile=${input[${#input[*]}-1]}
 	case $osname in
 	FreeBSD)
-		echo "Attempting to get file - ""${input[*]}"
-		echo "Attempting to save file to - ""$targetdir/$outputfile"
+		output "Attempting to get file - ""${input[*]}" 0
+		output "Attempting to save file to - ""$targetdir/$outputfile" 0
 		fetch "$quiet" -o "$targetdir/$outputfile" "${input[*]}"
 		status=$?
 		output "File get completed with status "$status $status
-		
 		((script_exit_code = script_exit_code + status))
 	;;
 	Linux)
-		echo "Attempting to get file - ""${input[*]}"
-		echo "Attempting to save file to - ""$targetdir/$outputfile"
+		output "Attempting to get file - ""${input[*]}" 0
+		output "Attempting to save file to - ""$targetdir/$outputfile" 0
 		wget "$quiet" --no-check-certificate -O "$targetdir/$outputfile" "${input[*]}"
 		status=$?
 		output "File get completed with status "$status $status
-		
 		((script_exit_code = script_exit_code + status))
 	;;
 	esac
@@ -287,6 +296,9 @@ do
 		if [ $windows = TRUE ]
 		then
 			sed -i 's/$/\r/' "$targetdir/$outputfile"
+			status=$?
+			output "Converion to Windows format complete with status "$status $status
+			((script_exit_code = script_exit_code + status))
 		fi
 		# If persist is TRUE, save parameters.
 		if [ $persist = TRUE ]
@@ -297,14 +309,21 @@ do
 		if [ $owner = TRUE ]
 		then
 			chown $newowner "$targetdir/$outputfile"
+			status=$?
+			output "Owner change complete with status "$status $status
+			((script_exit_code = script_exit_code + status))
 		fi
 		if [ $ownergroup = TRUE ]
 		then
 			chown :$newownergroup "$targetdir/$outputfile"
+			status=$?
+			output "Owner group change complete with status "$status $status
+			((script_exit_code = script_exit_code + status))
 		fi
 	fi
 done
 exec 3<&-
 
 # And exit
-script_exit "Script complete with exit code: "$script_exit_code
+output "Script complete with exit code: "$script_exit_code $script_exit_code
+script_exit
